from django.urls import path,include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),  
    path('shop/', views.shop, name='shop'),
    path('shop_detail/', views.shop_detail, name='shop_detail'),
    path('error/', views.error, name='error'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'), 
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('country/', views.country_list, name='country_list'),
    path('edit/<int:pk>/', views.country_edit, name='country_edit'),
    path('add/', views.country_add, name='country_add'),
    path('delete/<int:pk>/', views.country_delete, name='country_delete'),
    path('brand/', views.brand_list, name='brand_list'),
    path('brand_add/', views.brand_add, name='brand_add'),
    path('brand_edit/<int:pk>/', views.brand_edit, name='brand_edit'),
    path('brand_delete/<int:pk>/', views.brand_delete, name='brand_delete'),
    path('category/', views.category_list, name='category_list'),
    path('category_add/', views.category_add, name='category_add'),
    path('category_edit/<int:pk>/', views.category_edit, name='category_edit'),
    path('category_delete/<int:pk>/', views.category_delete, name='category_delete'),
    path('products/', views.products, name='products'),
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.product_add, name='product_add'),
    path('products/edit/<int:pk>/', views.product_edit, name='product_edit'),
    path('products/delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('products/search/', views.product_search, name='product_search'),
    path('products/all/', views.all_products, name='all_products'), 
    path('category/<int:category_id>/', views.category_products, name='category_products'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:item_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/add_all_to_cart/', views.add_all_to_cart, name='add_all_to_cart'),
    path('customer_register/', views.customer_register, name='customer_register'),
    path('customer_login/', views.customer_login, name='customer_login'),
    path('customer_logout/', views.customer_logout, name='customer_logout'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/update/<int:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.order_list, name='orders'),
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('invoice/<int:order_id>/', views.invoice_view, name='invoice_view'),
    path('pending_orders/', views.pending_orders, name='pending_orders'),
    path('verify_order/<int:order_id>/', views.verify_order, name='verify_order'),
    path('delivery_register/', views.delivery_partner_register, name='delivery_register'),
    path('delivery_login/', views.delivery_partner_login_view, name='delivery_login'),
    path('assign_orders/', views.assign_orders, name='assign_orders'),
    path('delivery_dashboard/', views.delivery_dashboard, name='delivery_dashboard'), 
    path('update_order_status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    path('contact/', views.contact_view, name='contact'),
    path('enquiries/', views.enquiries_view, name='enquiries'),
    path('contact/thank-you/', views.contact_thank_you, name='contact_thank_you'),
    path('shipping_management/', views.shipping_management, name='shipping_management'),
    path('subscribe/', views.subscribe_view, name='subscribe'),
    path('subscribe/thank-you/', views.subscription_thank_you, name='subscription_thank_you'),
    path('view_subscribers/', views.view_subscribers, name='view_subscribers'),
    path('send_email/', views.send_email_view, name='send_email_view'),
    path('view_customers/', views.view_customers, name='view_customers'),
    path('order_history/', views.order_history_view, name='order_history'),
    path('download_db/', views.download_db, name='download_db'),
    path('download_images/', views.download_images, name='download_images'),
    path('downloads/', views.download_page, name='downloads'),
    path('submit_feedback/<int:product_id>/', views.submit_feedback, name='submit_feedback'),
    path('feedback/', views.feedback_view, name='feedback'),
   
]
    


