# Generated by Django 5.1.3 on 2024-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0002_tbl_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('brand_name', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_country',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
