# Generated by Django 5.1.3 on 2024-11-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0003_tbl_brands_alter_tbl_country_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('category_name', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
