# Generated by Django 5.1.3 on 2024-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0009_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
