# Generated by Django 5.1.3 on 2024-11-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0012_payment_shippinginfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
