# Generated by Django 5.1.3 on 2024-11-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0014_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=100, null=True)),
                ('license_number', models.CharField(max_length=50)),
                ('pan_card_number', models.CharField(max_length=50)),
                ('aadhaar_number', models.CharField(max_length=50)),
                ('bike_reg_number', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=True)),
            ],
        ),
    ]
