# Generated by Django 5.1.3 on 2024-11-30 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0015_deliverypartner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypartner',
            name='partner',
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veg.deliverypartner'),
        ),
        migrations.AlterField(
            model_name='deliverypartner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
